
notifications:
  email: false

language: c
sudo: false

branches:
  only:
  - master

compiler:
  - gcc
  - clang
os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - texinfo
    - zlib1g-dev

script:
  - cd $TRAVIS_BUILD_DIR/binutils-gdb
  - ./configure --target=mipsel-unknown-linux-gnu --prefix=$TRAVIS_BUILD_DIR/binutils-gdb/cross/mips --with-system-zlib
  - make
  - make install
