notifications:
  email: false

language: cpp
sudo: false

branches:
  only:
  - master

compiler:
  - clang
os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-5.0		
    packages:
    - gcc-6
    - g++-6
    - clang-5.0
    - clang-tidy-5.0
    - llvm-5.0-dev
    - texinfo
    - zlib1g-dev
    - bear

install:
  - export CXX=clang++-5.0
  - export CC=clang-5.0
  - chmod +x $TRAVIS_BUILD_DIR/clean-commands.py

script:
  - cd $TRAVIS_BUILD_DIR/binutils-gdb
  - ./configure --target=mipsel-unknown-linux-gnu --prefix=$TRAVIS_BUILD_DIR/binutils-gdb/cross/mips --with-system-zlib
  - bear make > /dev/null
  - $TRAVIS_BUILD_DIR/clean-commands.py
  - run-clang-tidy-5.0.py -clang-tidy-binary clang-tidy-5.0 -header-filter='.*' -checks='*'
  - make install > /dev/null
