notifications:
  email: false

language: cpp
sudo: false
dist: bionic

branches:
  only:
  - master

compiler:
  - clang

os:
  - linux

addons:
  apt:
    sources:
    - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
      key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    packages:
    - clang-9
    - clang-tidy-9
    - python3
    - bear

script:
  - export CC=clang-9
  - export CXX=clang++-9
  - cd $TRAVIS_BUILD_DIR/binutils-gdb
  - ./configure --target=mipsel-unknown-linux-gnu --prefix=$TRAVIS_BUILD_DIR/binutils-gdb/cross/mips --with-system-zlib --with-python=python3
  - bear make MAKEINFO=true > /dev/null
  - run-clang-tidy-9.py -clang-tidy-binary clang-tidy-9 -header-filter='.*' '^((?!conftest).)*$' | grep -v "header-filter" --color=never
  - make MAKEINFO=true install > /dev/null
