notifications:
  email: false

language: cpp
sudo: required

branches:
  only:
  - master

compiler:
  - clang
os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-5.0		
    packages:
    - clang-5.0
    - clang-tidy-5.0
    - llvm-5.0-dev
    - texinfo
    - zlib1g-dev

install: 
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - cd $TRAVIS_BUILD_DIR/Bear
  - cmake .
  - make all
  - sudo make install

script:
  - export CXX=clang++-5.0
  - export CC=clang-5.0
  - cd $TRAVIS_BUILD_DIR/binutils-gdb
  - ./configure --target=mipsel-unknown-linux-gnu --prefix=$TRAVIS_BUILD_DIR/binutils-gdb/cross/mips --with-system-zlib
  - bear make
  - make install
  - run-clang-tidy.py -clang-tidy-binary clang-tidy-5.0 -header-filter='.*' -checks='-*,modernize-use-auto'
