name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '00 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
    steps:
    - name: Download
      run: git clone https://github.com/bminor/binutils-gdb
    - name: Install tools
      run: sudo apt-get install clang++-10 clang-tidy-10 bear
    - name: Configure
      working-directory: binutils-gdb
      run: ./configure --target=mipsel-unknown-linux-gnu --prefix=$TRAVIS_BUILD_DIR/binutils-gdb/cross/mips --with-system-zlib --with-python=python3
    - name: Build
      working-directory: binutils-gdb
      run: bear make MAKEINFO=true > /dev/null
    - name: Clang-Tidy
      working-directory: binutils-gdb
      run: run-clang-tidy-10.py -header-filter='.*' '^((?!conftest).)*$' | grep -v "header-filter" --color=never
    - name: Install
      working-directory: binutils-gdb
      run: make MAKEINFO=true install > /dev/null
