name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '00 15 * * *'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      CC: clang
      CXX: clang++
    steps:
    - name: Download
      run: git clone https://github.com/bminor/binutils-gdb --depth 1

    - name: Install Ubuntu tools
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install clang++-10 clang-tidy-10 bear
        echo "CC=clang-10" >> $GITHUB_ENV
        echo "CXX=clang++-10" >> $GITHUB_ENV

    - name: Configure
      working-directory: binutils-gdb
      run: ./configure --target=mipsel-unknown-linux-gnu --prefix=$GITHUB_WORKSPACE/binutils-gdb/cross/mips --with-system-zlib --with-python=python3
  
    - name: Build
      working-directory: binutils-gdb
      run: bear make MAKEINFO=true > /dev/null
    
    - name: Clang-Tidy
      if: matrix.os == 'ubuntu-latest'
      working-directory: binutils-gdb
      run: run-clang-tidy-10.py -clang-tidy-binary clang-tidy-10 -header-filter='.*' '^((?!conftest).)*$' | grep -v "header-filter" --color=never
    
    - name: Install
      working-directory: binutils-gdb
      run: make MAKEINFO=true install > /dev/null
